# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import pentagram.models


class Migration(migrations.Migration):

    dependencies = [
        ('pentagram', '0003_auto_20160913_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pentagram.models.photos_directory),
        ),
    ]
